// upskillingService.js
// Curated 15-Minute Micro-Refresher Upskilling Tracks for Returning Mothers

export const UPSKILLING_TRACKS = [
  {
    id: "uiux",
    label: "UI / UX Design & Product Thinking",
    shortLabel: "UI / UX Design",
    category: "Product Design",
    icon: "Layout",
    color: "#4C7053",
    tagline: "Master modern Figma workflows, design systems, and rapid wireframing.",
    targetRole: "Product Designer, UI/UX Consultant, UX Researcher",
    tasks: [
      {
        id: "uiux-mon",
        day: "Monday",
        name: "Figma Component Auto-Layout & Variants",
        mins: 15,
        tag: "Figma",
        drill: "Build a responsive card component in Figma using auto-layout (Shift+A) with Hug and Fill width constraints.",
        keyTakeaway: "Auto-layout components ensure rapid responsive design handoff.",
        done: false,
      },
      {
        id: "uiux-tue",
        day: "Tuesday",
        name: "WCAG Accessible Color Contrast & Typography Scale",
        mins: 15,
        tag: "Visuals",
        drill: "Audit 3 button states using the Contrast plugin to guarantee AA 4.5:1 ratio and set an 8pt baseline typography scale.",
        keyTakeaway: "Accessibility is a top requirement in modern tech design interviews.",
        done: false,
      },
      {
        id: "uiux-wed",
        day: "Wednesday",
        name: "User Journey & Empathy Pain-Point Mapping",
        mins: 15,
        tag: "UX Research",
        drill: "Map user thoughts, friction points, and opportunities across a 3-step mobile subscription flow.",
        keyTakeaway: "Proves user-first analytical thinking over just aesthetic styling.",
        done: false,
      },
      {
        id: "uiux-thu",
        day: "Thursday",
        name: "Interactive Prototyping & Smart Animate Noodles",
        mins: 15,
        tag: "Prototyping",
        drill: "Create interactive component states (default, hover, active, disabled) with smooth spring transitions.",
        keyTakeaway: "Interactive prototypes dramatically improve stakeholder presentations.",
        done: false,
      },
      {
        id: "uiux-fri",
        day: "Friday",
        name: "Design Tokens & Atomic Component Libraries",
        mins: 15,
        tag: "Design Systems",
        drill: "Organize color variables, spacing constants (4px/8px/16px/24px), and elevation tokens.",
        keyTakeaway: "Design token architecture is essential for large-scale engineering handoffs.",
        done: false,
      },
      {
        id: "uiux-sat",
        day: "Saturday",
        name: "UX Case Study Narrative & Portfolio Polish",
        mins: 20,
        tag: "Portfolio",
        drill: "Draft a crisp 3-paragraph summary: Problem statement, Research discovery, and Measurable business impact.",
        keyTakeaway: "Recruiters look for business outcomes, not just screenshot galleries.",
        done: false,
      },
    ],
  },
  {
    id: "python",
    label: "Python & AI Engineering",
    shortLabel: "Python & AI",
    category: "Software & AI",
    icon: "Code2",
    color: "#2B5A75",
    tagline: "Build practical automation scripts, API endpoints, and AI prompt pipelines.",
    targetRole: "Python Developer, AI Solutions Associate, Automation Engineer",
    tasks: [
      {
        id: "python-mon",
        day: "Monday",
        name: "Python Core Syntax & List Comprehensions",
        mins: 15,
        tag: "Python Core",
        drill: "Write 5 clean list comprehensions and dictionary mappings to clean raw JSON data.",
        keyTakeaway: "Pythonic idioms demonstrate professional coding maturity.",
        done: false,
      },
      {
        id: "python-tue",
        day: "Tuesday",
        name: "Automating Spreadsheets & CSV Processing",
        mins: 15,
        tag: "Automation",
        drill: "Write a 20-line script using Python's `csv` module to aggregate monthly expense items into summary totals.",
        keyTakeaway: "Automation scripts provide immediate freelance value to small businesses.",
        done: false,
      },
      {
        id: "python-wed",
        day: "Wednesday",
        name: "FastAPI Micro-Endpoint & Pydantic Validation",
        mins: 15,
        tag: "FastAPI",
        drill: "Create a lightweight GET and POST endpoint with typed request body validation in FastAPI.",
        keyTakeaway: "FastAPI is the modern industry standard for Python microservices.",
        done: false,
      },
      {
        id: "python-thu",
        day: "Thursday",
        name: "Pandas Dataframe Wrangling & Cleaning",
        mins: 15,
        tag: "Pandas",
        drill: "Load a sample CSV, fill missing NaN values, and calculate grouped averages with `.groupby()`. ",
        keyTakeaway: "Pandas data wrangling is essential across data engineering and backend roles.",
        done: false,
      },
      {
        id: "python-fri",
        day: "Friday",
        name: "Gemini / LLM API Prompt Orchestration",
        mins: 15,
        tag: "AI Integration",
        drill: "Send a structured prompt to Gemini Flash API with JSON mode enabled to extract key insights.",
        keyTakeaway: "AI API engineering is one of the highest-demand skills in 2026 hiring.",
        done: false,
      },
      {
        id: "python-sat",
        day: "Saturday",
        name: "GitHub Portfolio Repo & Unit Testing with Pytest",
        mins: 20,
        tag: "Dev Best Practices",
        drill: "Write 3 unit tests in pytest and push clean code with a descriptive README to GitHub.",
        keyTakeaway: "Tested GitHub repositories stand out 10x over unverified resume claims.",
        done: false,
      },
    ],
  },
  {
    id: "data",
    label: "Data & Business Analytics",
    shortLabel: "Data Analytics",
    category: "Analytics & BI",
    icon: "BarChart3",
    color: "#6D4C41",
    tagline: "Transform raw spreadsheets into executive dashboards and SQL insights.",
    targetRole: "Business Analyst, Data Operations Specialist, BI Developer",
    tasks: [
      {
        id: "data-mon",
        day: "Monday",
        name: "Modern Excel: XLOOKUP & Dynamic Array Formulas",
        mins: 15,
        tag: "Excel Pro",
        drill: "Replace legacy nested IFs and VLOOKUPs with `=XLOOKUP()` and `=FILTER()` dynamic arrays.",
        keyTakeaway: "Mastering modern Excel saves hours on corporate reporting tasks.",
        done: false,
      },
      {
        id: "data-tue",
        day: "Tuesday",
        name: "SQL Queries: JOINs, Aggregates & Group By",
        mins: 15,
        tag: "SQL",
        drill: "Write a SQL query joining `customers` and `orders` to find top 10 revenue-generating accounts.",
        keyTakeaway: "SQL is requested on over 80% of remote data and operations job postings.",
        done: false,
      },
      {
        id: "data-wed",
        day: "Wednesday",
        name: "Power BI / Tableau Interactive KPI Cards",
        mins: 15,
        tag: "Power BI",
        drill: "Build a revenue vs. monthly target gauge card with dynamic month-over-month percentage change.",
        keyTakeaway: "Visual cards allow non-technical executives to absorb key insights immediately.",
        done: false,
      },
      {
        id: "data-thu",
        day: "Thursday",
        name: "Cohort Retention & Churn Risk Analysis",
        mins: 15,
        tag: "Business Metrics",
        drill: "Calculate weekly customer retention percentages and identify month-2 drop-off inflection points.",
        keyTakeaway: "Cohort modeling demonstrates strategic product and commercial understanding.",
        done: false,
      },
      {
        id: "data-fri",
        day: "Friday",
        name: "Data Storytelling: 1-Page Stakeholder Brief",
        mins: 15,
        tag: "Executive Comms",
        drill: "Convert 3 analytical charts into 3 bullet points: Finding, Business Root Cause, and Recommended Action.",
        keyTakeaway: "Great analysts communicate actionable decisions, not just raw charts.",
        done: false,
      },
      {
        id: "data-sat",
        day: "Saturday",
        name: "Public Dashboard Link & Resume Metric Polish",
        mins: 20,
        tag: "Portfolio",
        drill: "Publish an interactive Looker Studio or Power BI dashboard and add the live link to your resume.",
        keyTakeaway: "A live clickable dashboard link proves instant technical competence.",
        done: false,
      },
    ],
  },
  {
    id: "pm",
    label: "Product Management & Agile",
    shortLabel: "Product Management",
    category: "Product Leadership",
    icon: "Briefcase",
    color: "#7E5265",
    tagline: "Lead feature roadmaps, write crisp PRDs, and master agile team prioritization.",
    targetRole: "Product Manager, Associate PM, Scrum Master, Product Owner",
    tasks: [
      {
        id: "pm-mon",
        day: "Monday",
        name: "1-Page Product Requirement Document (PRD)",
        mins: 15,
        tag: "PRD Specs",
        drill: "Draft a 1-pager covering: Problem Statement, User Persona, Success Metrics, and Non-Goals.",
        keyTakeaway: "Concise 1-page PRDs ensure rapid team alignment without meeting bloat.",
        done: false,
      },
      {
        id: "pm-tue",
        day: "Tuesday",
        name: "User Stories & Gherkin Acceptance Criteria",
        mins: 15,
        tag: "Agile Specs",
        drill: "Write 3 user stories formatted as 'As a [user], I want [action] so that [benefit]' with Given-When-Then rules.",
        keyTakeaway: "Clear acceptance criteria eliminate engineering rework during sprint reviews.",
        done: false,
      },
      {
        id: "pm-wed",
        day: "Wednesday",
        name: "North Star Metric & KPI Tree Mapping",
        mins: 15,
        tag: "Metrics",
        drill: "Break down an overarching North Star (e.g., Weekly Active Users) into input drivers: Retention, Acquisition, Referral.",
        keyTakeaway: "KPI trees allow PMs to identify which metric lever to pull.",
        done: false,
      },
      {
        id: "pm-thu",
        day: "Thursday",
        name: "RICE / MoSCoW Backlog Prioritization",
        mins: 15,
        tag: "Prioritization",
        drill: "Score 4 feature requests using Reach x Impact x Confidence / Effort to rank the next sprint backlog.",
        keyTakeaway: "Data-backed scoring prevents subjective executive feature requests.",
        done: false,
      },
      {
        id: "pm-fri",
        day: "Friday",
        name: "Competitive Feature Teardown & Gap Matrix",
        mins: 15,
        tag: "Strategy",
        drill: "Compare 2 competitor onboarding flows and document 3 differentiation opportunities.",
        keyTakeaway: "Competitive awareness helps position products winningly in crowded markets.",
        done: false,
      },
      {
        id: "pm-sat",
        day: "Saturday",
        name: "Product Sense Mock Case Study Prep",
        mins: 20,
        tag: "Interview Prep",
        drill: "Practice answering: 'How would you improve a remote collaboration tool for working parents?' using structured frameworks.",
        keyTakeaway: "Structured communication is the #1 evaluated criteria in PM returnship interviews.",
        done: false,
      },
    ],
  },
  {
    id: "selffinancing",
    label: "Self-Financing & Freelance Mastery",
    shortLabel: "Freelance & Consulting",
    category: "Independent Income",
    icon: "DollarSign",
    color: "#3F6253",
    tagline: "Build recurring remote freelance income, client proposals, and digital services.",
    targetRole: "Independent Consultant, High-Ticket Freelancer, Agency Partner",
    tasks: [
      {
        id: "self-mon",
        day: "Monday",
        name: "Niche Positioning & Irresistible Offer Statement",
        mins: 15,
        tag: "Positioning",
        drill: "Craft your 1-sentence value proposition: 'I help [specific niche] achieve [measurable outcome] via [core skill].'",
        keyTakeaway: "Specialized positioning commands 3x higher rates than generalist services.",
        done: false,
      },
      {
        id: "self-tue",
        day: "Tuesday",
        name: "High-Ticket 3-Tier Service Packaging",
        mins: 15,
        tag: "Pricing",
        drill: "Structure your service into 3 packages: Starter ($500), Growth ($1,500), and Full-Service Monthly Retainer ($3,000).",
        keyTakeaway: "Tiered packages anchor clients toward the high-margin middle and top tiers.",
        done: false,
      },
      {
        id: "self-wed",
        day: "Wednesday",
        name: "Client Outreach Pitch & Discovery Call Script",
        mins: 15,
        tag: "Sales Outreach",
        drill: "Draft a 4-sentence personalized cold message pointing out 1 quick win you can deliver for a prospective client.",
        keyTakeaway: "Direct value-add messages convert 5x better than generic portfolio links.",
        done: false,
      },
      {
        id: "self-thu",
        day: "Thursday",
        name: "Scope Creep Protection & Milestone Contracts",
        mins: 15,
        tag: "Contracts",
        drill: "Add 50% upfront deposit terms and clear revision limits (2 rounds max) to your client agreement template.",
        keyTakeaway: "Clear contracts protect your energy, payment security, and schedule flexibility.",
        done: false,
      },
      {
        id: "self-fri",
        day: "Friday",
        name: "Asynchronous Client Onboarding & Loom Updates",
        mins: 15,
        tag: "Client Success",
        drill: "Create a 3-step Notion client portal template and practice recording a 2-minute project summary walkthrough.",
        keyTakeaway: "Asynchronous updates delight clients while protecting quiet baby rest windows.",
        done: false,
      },
      {
        id: "self-sat",
        day: "Saturday",
        name: "LinkedIn Recommendation & Referral System",
        mins: 20,
        tag: "Referrals",
        drill: "Draft an automated follow-up email asking happy clients for a 2-sentence testimonial and peer introductions.",
        keyTakeaway: "80% of top freelancers get their best clients via existing client referrals.",
        done: false,
      },
    ],
  },
  {
    id: "webdev",
    label: "Modern Web Development (React & JS)",
    shortLabel: "React Web Dev",
    category: "Software Development",
    icon: "Globe",
    color: "#1E5F74",
    tagline: "Build dynamic React apps, reusable hooks, and full-stack web applications.",
    targetRole: "Frontend Developer, Full-Stack Engineer, React Specialist",
    tasks: [
      {
        id: "webdev-mon",
        day: "Monday",
        name: "Modern JavaScript (ES6+) Syntax Refresher",
        mins: 15,
        tag: "JavaScript",
        drill: "Practice object destructuring, rest/spread operators, array `.map()`, and optional chaining `?.`.",
        keyTakeaway: "ES6+ fluency is tested on every frontend technical assessment.",
        done: false,
      },
      {
        id: "webdev-tue",
        day: "Tuesday",
        name: "React Hooks Mastery: useState, useEffect & useRef",
        mins: 15,
        tag: "React Hooks",
        drill: "Build a custom hook `useLocalStorage` that syncs React state with browser storage seamlessly.",
        keyTakeaway: "Custom hooks show strong modular frontend architectural skills.",
        done: false,
      },
      {
        id: "webdev-wed",
        day: "Wednesday",
        name: "Tailwind CSS Utility Styling & Responsive Layouts",
        mins: 15,
        tag: "Tailwind CSS",
        drill: "Style an elegant dark-mode glassmorphic modal with smooth hover micro-transitions in Tailwind.",
        keyTakeaway: "Tailwind allows you to build stunning custom UIs at 5x the speed of vanilla CSS.",
        done: false,
      },
      {
        id: "webdev-thu",
        day: "Thursday",
        name: "REST API Integration, Skeletons & Error Handling",
        mins: 15,
        tag: "API Integration",
        drill: "Fetch async data with `fetch()`, render shimmer loading skeletons, and catch network failure states gracefully.",
        keyTakeaway: "Robust error handling is what separates junior coders from production engineers.",
        done: false,
      },
      {
        id: "webdev-fri",
        day: "Friday",
        name: "Context API & Global State Architecture",
        mins: 15,
        tag: "State Management",
        drill: "Create a lightweight React context provider with a reducer to manage shopping cart / user auth state.",
        keyTakeaway: "Clean state management prevents prop drilling across large web apps.",
        done: false,
      },
      {
        id: "webdev-sat",
        day: "Saturday",
        name: "1-Click Vercel / Netlify Deployment & Live URL",
        mins: 20,
        tag: "Deployment",
        drill: "Push your React app to GitHub, connect to Vercel, and verify the automated CI/CD build deployment.",
        keyTakeaway: "A live public web URL allows hiring managers to try your code immediately on their phone.",
        done: false,
      },
    ],
  },
  {
    id: "marketing",
    label: "Digital Marketing & Growth Funnels",
    shortLabel: "Growth Marketing",
    category: "Marketing & Growth",
    icon: "TrendingUp",
    color: "#8C4A32",
    tagline: "Drive organic search traffic, automated email flows, and paid performance ads.",
    targetRole: "Growth Marketer, Content Strategist, Performance Marketing Specialist",
    tasks: [
      {
        id: "mktg-mon",
        day: "Monday",
        name: "SEO Keyword Research & Search Intent Mapping",
        mins: 15,
        tag: "SEO",
        drill: "Identify 5 high-intent long-tail keywords with low search difficulty using Google Trends & Keyword Planner.",
        keyTakeaway: "Targeting high-intent search terms drives qualified inbound leads organically.",
        done: false,
      },
      {
        id: "mktg-tue",
        day: "Tuesday",
        name: "High-Converting Ad Copy & Hook Frameworks",
        mins: 15,
        tag: "Copywriting",
        drill: "Write 3 ad variations using the Hook-Story-Offer framework for LinkedIn / Meta sponsored campaigns.",
        keyTakeaway: "Compelling scroll-stopping hooks cut customer acquisition cost in half.",
        done: false,
      },
      {
        id: "mktg-wed",
        day: "Wednesday",
        name: "Automated 5-Email Welcome Nurture Sequence",
        mins: 15,
        tag: "Email Automation",
        drill: "Outline a 5-day welcome sequence: Welcome + Freebie, Origin Story, Case Study, FAQ, and Call to Action.",
        keyTakeaway: "Automated email sequences convert cold subscribers into warm paying clients on autopilot.",
        done: false,
      },
      {
        id: "mktg-thu",
        day: "Thursday",
        name: "Omnichannel Content Repurposing Engine",
        mins: 15,
        tag: "Content Strategy",
        drill: "Take 1 insightful case study and adapt it into a LinkedIn carousel, a Twitter/X thread, and a newsletter snippet.",
        keyTakeaway: "Repurposing allows you to maintain high social presence with only 2 hours of weekly effort.",
        done: false,
      },
      {
        id: "mktg-fri",
        day: "Friday",
        name: "Google Analytics 4 (GA4) Event & Goal Tracking",
        mins: 15,
        tag: "Analytics",
        drill: "Set up a custom GA4 event tag to measure primary CTA button clicks and calculate lead conversion rates.",
        keyTakeaway: "Data-driven marketing proves direct ROI and attribution to leadership.",
        done: false,
      },
      {
        id: "mktg-sat",
        day: "Saturday",
        name: "Growth Experiment Matrix & A/B Testing Log",
        mins: 20,
        tag: "Growth Hacking",
        drill: "Document 3 growth hypotheses with expected impact, confidence score, and statistical test duration.",
        keyTakeaway: "Growth teams hire marketers who think like experimental scientists.",
        done: false,
      },
    ],
  },
  {
    id: "leadership",
    label: "Executive Leadership & Returnee Confidence",
    shortLabel: "Leadership & Confidence",
    category: "Career Strategy",
    icon: "Award",
    color: "#5C4D7D",
    tagline: "Own your maternity break as leadership experience, negotiate salary, and interview with authority.",
    targetRole: "Team Lead, Director, Returning Senior Manager, Operations Lead",
    tasks: [
      {
        id: "lead-mon",
        day: "Monday",
        name: "Translating the Maternity Break into Leadership Skills",
        mins: 15,
        tag: "Career Story",
        drill: "Write a 90-second talking point reframing your career pause around crisis management, ruthless prioritization, and empathy.",
        keyTakeaway: "Own your motherhood journey with pride and authority rather than apologizing for gap years.",
        done: false,
      },
      {
        id: "lead-tue",
        day: "Tuesday",
        name: "Executive Presence & Authoritative Intro Pitch",
        mins: 15,
        tag: "Executive Presence",
        drill: "Practice delivering a 60-second self-introduction focusing on your top 2 career achievements without filler words.",
        keyTakeaway: "First impressions in the opening 2 minutes set the tone for senior-level evaluations.",
        done: false,
      },
      {
        id: "lead-wed",
        day: "Wednesday",
        name: "Behavioral STAR Method Interview Mastery",
        mins: 15,
        tag: "Interview Prep",
        drill: "Draft 2 stories using Situation-Task-Action-Result addressing difficult stakeholder conflicts and strategic turnarounds.",
        keyTakeaway: "STAR frameworks ensure structured, memorable interview responses under pressure.",
        done: false,
      },
      {
        id: "lead-thu",
        day: "Thursday",
        name: "Salary & Hybrid Flexibility Negotiation Scripts",
        mins: 15,
        tag: "Negotiation",
        drill: "Prepare 3 scripts: Countering a lowball offer, negotiating core hours, and securing remote work flexibility.",
        keyTakeaway: "Negotiating from market value rather than previous salary commands significant compensation bumps.",
        done: false,
      },
      {
        id: "lead-fri",
        day: "Friday",
        name: "Strategic Warm Outreach & Reconnect Strategy",
        mins: 15,
        tag: "Networking",
        drill: "Draft 3 genuine reconnect messages to former managers, mentors, and peers to reignite your warm network.",
        keyTakeaway: "Over 70% of executive returnees land roles through warm network referrals.",
        done: false,
      },
      {
        id: "lead-sat",
        day: "Saturday",
        name: "30-60-90 Day Return-to-Work Gameplan",
        mins: 20,
        tag: "Strategic Roadmap",
        drill: "Outline your 30-day listening tour, 60-day process optimizations, and 90-day key strategic deliverables.",
        keyTakeaway: "Bringing a 30-60-90 day plan to final-round interviews instantly wins executive confidence.",
        done: false,
      },
    ],
  },
  {
    id: "cloud",
    label: "Cloud Fundamentals & DevOps",
    shortLabel: "Cloud & DevOps",
    category: "Cloud Engineering",
    icon: "Cloud",
    color: "#2C6B6F",
    tagline: "Master AWS core services, Docker containers, and automated CI/CD workflows.",
    targetRole: "Cloud Engineer, DevOps Associate, Infrastructure Specialist",
    tasks: [
      {
        id: "cloud-mon",
        day: "Monday",
        name: "Cloud Architecture: IaaS vs PaaS vs Serverless",
        mins: 15,
        tag: "Cloud Basics",
        drill: "Map when to use AWS EC2 (VM), AWS ECS/Fargate (Containers), and AWS Lambda (Serverless).",
        keyTakeaway: "Architectural trade-offs demonstrate solid systems-level decision making.",
        done: false,
      },
      {
        id: "cloud-tue",
        day: "Tuesday",
        name: "AWS S3 Bucket Security & Permissions",
        mins: 15,
        tag: "AWS Storage",
        drill: "Configure an S3 bucket with strict public access blocks, server-side encryption, and lifecycle tiering.",
        keyTakeaway: "Cloud security and least-privilege IAM policies are top technical requirements.",
        done: false,
      },
      {
        id: "cloud-wed",
        day: "Wednesday",
        name: "Docker Containerization & Dockerfile Basics",
        mins: 15,
        tag: "Docker",
        drill: "Write a multi-stage Dockerfile to package a lightweight Node or Python web service.",
        keyTakeaway: "Containerization guarantees that code runs identically across dev and cloud environments.",
        done: false,
      },
      {
        id: "cloud-thu",
        day: "Thursday",
        name: "CI/CD Pipelines with GitHub Actions",
        mins: 15,
        tag: "CI / CD",
        drill: "Create `.github/workflows/main.yml` to automatically run tests and linter on every pull request.",
        keyTakeaway: "Automated pipelines save teams hours of manual verification and release friction.",
        done: false,
      },
      {
        id: "cloud-fri",
        day: "Friday",
        name: "CloudWatch Monitoring & Error Alerting",
        mins: 15,
        tag: "Monitoring",
        drill: "Configure alarm thresholds for HTTP 500 error rates and high CPU spikes with email notifications.",
        keyTakeaway: "Proactive monitoring prevents costly enterprise production downtime.",
        done: false,
      },
      {
        id: "cloud-sat",
        day: "Saturday",
        name: "Serverless Function Deploy & Cloud Architecture Deck",
        mins: 20,
        tag: "Serverless",
        drill: "Deploy an AWS Lambda function triggered by an API Gateway endpoint and document the cloud architecture.",
        keyTakeaway: "Hands-on cloud deployments prove real-world infrastructure competence.",
        done: false,
      },
    ],
  },
  {
    id: "java",
    label: "Java & Enterprise Backend",
    shortLabel: "Java Development",
    category: "Enterprise Software",
    icon: "Terminal",
    color: "#8B4513",
    tagline: "Build enterprise Spring Boot microservices, REST APIs, and database models.",
    targetRole: "Java Developer, Backend Engineer, Enterprise Software Consultant",
    tasks: [
      {
        id: "java-mon",
        day: "Monday",
        name: "Java OOP & Design Principles Refresher",
        mins: 15,
        tag: "Core Java",
        drill: "Implement polymorphism, encapsulation, and interface contracts for a clean payment gateway model.",
        keyTakeaway: "Solid OOP principles remain the foundation of all enterprise Java roles.",
        done: false,
      },
      {
        id: "java-tue",
        day: "Tuesday",
        name: "Java 17 Streams & Functional Collections",
        mins: 15,
        tag: "Modern Java",
        drill: "Use `.filter()`, `.map()`, `.reduce()`, and `.collect(Collectors.toList())` to process customer lists cleanly.",
        keyTakeaway: "Functional streams eliminate verbose for-loops and reduce bug surface.",
        done: false,
      },
      {
        id: "java-wed",
        day: "Wednesday",
        name: "Spring Boot REST Controller & Dependency Injection",
        mins: 15,
        tag: "Spring Boot",
        drill: "Build a `@RestController` with `@Service` and `@Autowired` dependency injection to serve user profiles.",
        keyTakeaway: "Spring Boot is the most widely adopted enterprise Java framework globally.",
        done: false,
      },
      {
        id: "java-thu",
        day: "Thursday",
        name: "Spring Data JPA & Hibernate Repository Queries",
        mins: 15,
        tag: "Database JPA",
        drill: "Create an `@Entity` class and `JpaRepository` interface with custom `@Query` JPQL search methods.",
        keyTakeaway: "Spring Data JPA eliminates 90% of boilerplate SQL database code.",
        done: false,
      },
      {
        id: "java-fri",
        day: "Friday",
        name: "Unit Testing with JUnit 5 & Mockito Mocks",
        mins: 15,
        tag: "Testing",
        drill: "Write unit tests using `@Mock`, `@InjectMocks`, and `when(...).thenReturn(...)` to test service methods.",
        keyTakeaway: "Enterprise teams heavily evaluate test-driven development in technical screens.",
        done: false,
      },
      {
        id: "java-sat",
        day: "Saturday",
        name: "Spring Security JWT Token Authentication",
        mins: 20,
        tag: "Security",
        drill: "Understand how JWT security filters authenticate incoming bearer tokens and protect endpoints.",
        keyTakeaway: "Security knowledge is a major differentiator in senior backend engineer interviews.",
        done: false,
      },
    ],
  },
];

/**
 * Returns a specific upskilling track by ID
 */
export function getUpskillingTrack(trackId) {
  return UPSKILLING_TRACKS.find((t) => t.id === trackId) || UPSKILLING_TRACKS[0];
}

/**
 * Returns all upskilling tracks
 */
export function getAllUpskillingTracks() {
  return UPSKILLING_TRACKS;
}
